# bosh -e vsphere ucc cloud-config.yml
# 3,$!bosh int -
azs:
- cloud_properties:
    datacenters:
    - clusters:
      - cl:
          resource_pool: BOSH
      name: dc
  cpi: vsphere
  name: vsphere
- cloud_properties:
    availability_zone: us-east-1a
  cpi: aws
  name: aws
- cpi: azure
  name: azure
- cloud_properties:
    zone: us-central1-b
  cpi: google
  name: google
compilation:
  az: vsphere
  network: vsphere-guest
  reuse_compilation_vms: true
  vm_type: compilation
  workers: 5
disk_types:
- disk_size: 1024
  name: default
- disk_size: 1024
  name: 1G
- disk_size: 2048
  name: 2G
- disk_size: 3072
  name: 3G
- disk_size: 4096
  name: 4G
- disk_size: 5120
  name: 5G
- disk_size: 6144
  name: 6G
- cloud_properties:
    type: pd-ssd
  disk_size: 5120
  name: google-db
networks:
- name: aws-private
  subnets:
  - azs:
    - aws
    cloud_properties:
      security_groups:
      - default
      subnet: subnet-1c90ef6b
    dns:
    - 10.0.0.2
    gateway: 10.0.0.1
    range: 10.0.0.0/24
    reserved:
    - 10.0.0.2 - 10.0.0.6
  type: manual
- name: aws-public
  type: vip
- name: azure-private
  subnets:
  - azs:
    - azure
    cloud_properties:
      subnet_name: bosh
      virtual_network_name: boshnet
    dns:
    - 168.63.129.16
    gateway: 10.0.0.1
    range: 10.0.0.0/24
    reserved:
    - 10.0.0.2-10.0.0.3
  type: manual
- name: azure-public
  type: vip
- name: google-private
  subnets:
  - azs:
    - google
    cloud_properties:
      network_name: cf
      tags:
      - cf-internal
      - cf-bosh
    dns:
    - 10.128.0.2
    - 8.8.8.8
    gateway: 10.128.0.1
    range: 10.128.0.0/20
    reserved:
    - 10.128.0.2
    - 10.128.0.3
  type: manual
- name: google-public
  type: vip
- name: vsphere-guest
  subnets:
  - azs:
    - vsphere
    cloud_properties:
      name: Guest
    dns:
    - 10.2.0.1
    - 8.8.8.8
    gateway: 10.2.0.1
    range: 10.2.0.0/24
    reserved:
    - 10.2.0.1-10.2.0.200
    - 10.2.0.251-10.2.0.255
  type: manual
vm_types:
- cloud_properties:
    cpu: 1
    disk: 10240
    ram: 1024
  name: micro
- cloud_properties:
    cpu: 2
    disk: 10240
    ram: 8192
  name: small
- cloud_properties:
    cpu: 4
    disk: 16_384
    ram: 4096
  name: compilation
- cloud_properties:
    cpu: 4
    disk: 65536
    ram: 8192
  name: concourse-workers
- cloud_properties:
    cpu: 2
    disk: 11264
    ram: 16384
  name: small-highmem-low-cpu
- cloud_properties:
    ephemeral_disk:
      use_root_disk: true
    instance_type: Standard_B1S
  name: standard_b1s
- cloud_properties:
    ephemeral_disk:
      size: 4000
      type: gp2
    instance_type: t2.micro
  name: t2.micro
- cloud_properties:
    ephemeral_disk:
      size: 4000
      type: gp2
    instance_type: t3.micro
  name: t3.micro
- cloud_properties:
    ephemeral_disk:
      size: 4000
      type: gp2
    instance_type: t3.nano
  name: t3.nano
- cloud_properties:
    ephemeral_disk:
      size: 4000
      type: gp2
    instance_type: t3a.nano
  name: t3a.nano
- cloud_properties:
    machine_type: g1-small
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: g1-small
- cloud_properties:
    ram: 2816
    cpu: 1
    root_disk_size_gb: 12
    root_disk_type: pd-ssd
  name: concourse
- cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 10
    root_disk_type: pd-standard
  name: n1-standard-1
