# bosh -e vsphere ucc cloud-config.yml
# 3,$!bosh int -
azs:
- cloud_properties:
    datacenters:
    - clusters:
      - cl:
          resource_pool: BOSH
      name: dc
  name: vsphere
compilation:
  az: vsphere
  network: vsphere-subnet
  reuse_compilation_vms: true
  vm_type: compilation
  workers: 15
disk_types:
- disk_size: 1024
  name: default
networks:
- name: vsphere-subnet
  subnets:
  - azs:
    - vsphere
    cloud_properties:
      name: BOSH
    dns:
    - 10.9.16.1
    - 8.8.8.8
    gateway: 10.9.16.1
    range: 10.9.16.0/20
    reserved:
    - 10.9.16.1-10.9.16.19
    static:
    - 10.9.16.20-10.9.16.29
  type: manual
vm_extensions: []
vm_types:
- cloud_properties:
    cpu: 1
    disk: 10240
    ram: 1024
  name: micro
- cloud_properties:
    cpu: 2
    disk: 10240
    ram: 2048
  name: small
- cloud_properties:
    cpu: 4
    disk: 16384
    ram: 4096
  name: compilation
- cloud_properties:
    cpu: 4
    disk: 10240
    ram: 4096
  name: medium
- cloud_properties:
    cpu: 4
    disk: 204800
    ram: 8192
  name: concourse-workers
- cloud_properties:
    cpu: 8
    disk: 32768
    ram: 16384
  name: large
- cloud_properties:
    cpu: 8
    disk: 32768
    ram: 32768
  name: xlarge-1
- cloud_properties:
    cpu: 8
    disk: 32768
    ram: 32768
  name: xlarge-2
