# manifest for BOSH performance testing
name: dummy

releases: []

stemcells:
- alias: ubuntu
  os: ubuntu-xenial
  version: 621.23

update:
  canaries: 0
  max_in_flight: 10
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000

instance_groups:
- name: dummy-ubuntu
  jobs: []
  instances: 1
#  vm_type: default
  vm_type: small
  stemcell: ubuntu
#  azs: [z1]
  azs: [vsphere]
  networks:
#  - name: default
  - name: vsphere-guest
