# bosh -d dummy deploy dummy.yml
name: dummy

releases: []

stemcells:
- alias: bionic
  os: ubuntu-bionic
  version: latest
- alias: xenial-456
  os: ubuntu-xenial
  version: latest
- alias: xenial
  os: ubuntu-xenial
  version: latest
- alias: jammy
  os: ubuntu-jammy
  version: latest
- alias: windows
  os: windows2019
  version: latest

update:
  canaries: 0
  max_in_flight: 10
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000

instance_groups:
- azs:
  - vsphere
  instances: 1
  jobs: []
  name: xenial-456
  networks:
  - name: vsphere-guest
  stemcell: xenial-456
  vm_type: small
- azs:
  - vsphere
  instances: 1
  jobs: []
  name: xenial
  networks:
  - name: vsphere-guest
  stemcell: xenial
  vm_extensions:
  # - two-cores-per-socket
  # - disk-enable-uuid
  # - change-block-tracking
  - precision-clock
  vm_type: small
- azs:
  - vsphere
  instances: 1
  jobs: []
  name: bionic
  networks:
  - name: vsphere-guest
  stemcell: bionic
  vm_extensions:
  - anti-affinity-mysql
  vm_type: small
- azs:
  - vsphere
  instances: 1
  jobs: []
  name: jammy
  networks:
  - name: vsphere-guest
  stemcell: jammy
  vm_extensions:
  - anti-affinity-mysql
  vm_type: small
- azs:
  - vsphere
  instances: 1
  jobs: []
  name: windows
  networks:
  - name: vsphere-guest
  stemcell: windows
  vm_type: compilation
