# bosh -d dummy deploy dummy.yml
name: dummy

releases:
- name: "os-conf"
  version: latest

add_user_cunnie: &add_user_cunnie
  name: user_add
  properties:
    users:
    - name: cunnie
      public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIWiAzxc4uovfaphO0QVC2w00YmzrogUpjAzvuqaQ9tD
        cunnie@nono.io
  release: os-conf

stemcells:
- alias: jammy
  os: ubuntu-jammy
  version: latest

update:
  canaries: 0
  max_in_flight: 32
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000

instance_groups:
- azs:
  - vsphere
  instances: 1
  jobs:
  - *add_user_cunnie
  name: jammy
  networks:
  - name: vsphere-subnet
  stemcell: jammy
  vm_type: small
