# bosh -d dummy deploy dummy.yml
name: dummy

releases:
- name: "os-conf"
  version: latest

add_user_cunnie: &add_user_cunnie
  name: user_add
  properties:
    users:
    - name: cunnie
      public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIWiAzxc4uovfaphO0QVC2w00YmzrogUpjAzvuqaQ9tD
        cunnie@nono.io
  release: os-conf

stemcells:
- alias: bionic
  os: ubuntu-bionic
  version: latest
- alias: xenial
  os: ubuntu-xenial
  version: latest
- alias: jammy
  os: ubuntu-jammy
  version: latest
- alias: jammy-199
  os: ubuntu-jammy
  version: 1.199
- alias: windows
  os: windows2019
  version: latest

update:
  canaries: 0
  max_in_flight: 32
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000

instance_groups:
- azs:
  - vsphere
  instances: 1
  jobs:
  - *add_user_cunnie
  name: xenial
  networks:
  - name: vsphere-guest
  stemcell: xenial
  vm_extensions:
  # - two-cores-per-socket
  # - disk-enable-uuid
  # - change-block-tracking
  - precision-clock
  vm_type: small
- azs:
  - vsphere
  instances: 1
  jobs:
  - *add_user_cunnie
  name: bionic
  networks:
  - name: vsphere-guest
  stemcell: bionic
  vm_extensions:
  - two-cores-per-socket
  # - anti-affinity-mysql # Difficult to do ESXi maintenance; won't migrate off
  vm_type: small
- azs:
  - vsphere
  instances: 1
  jobs:
  - *add_user_cunnie
  - name: auditd
    properties:
      pre_start_delay: 2
    release: os-conf
  name: jammy
  networks:
  - name: vsphere-guest
  stemcell: jammy
  vm_extensions:
  - disk-enable-uuid
  # - anti-affinity-mysql # Difficult to do ESXi maintenance; won't migrate off
  vm_type: small
- azs:
  - vsphere
  instances: 1
  jobs:
  - *add_user_cunnie
  - name: auditd
    properties:
      pre_start_delay: 2
    release: os-conf
  name: jammy-199
  networks:
  - name: vsphere-guest
  stemcell: jammy-199
  vm_extensions:
  - disk-enable-uuid
  # - anti-affinity-mysql # Difficult to do ESXi maintenance; won't migrate off
  vm_type: small
- azs:
  - vsphere
  instances: 1
  jobs: []
  name: windows
  networks:
  - name: vsphere-guest
  stemcell: windows
  vm_type: compilation
