# bosh -d dummy deploy dummy.yml
name: dummy

releases:
- name: "os-conf"
  version: latest

add_user_cunnie: &add_user_cunnie
  name: user_add
  properties:
    users:
    - name: cunnie
      public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIWiAzxc4uovfaphO0QVC2w00YmzrogUpjAzvuqaQ9tD
        cunnie@nono.io
  release: os-conf

stemcells:
- alias: bionic
  os: ubuntu-bionic
  version: latest
- alias: xenial
  os: ubuntu-xenial
  version: latest
- alias: jammy
  os: ubuntu-jammy
  version: latest
- alias: noble
  os: ubuntu-noble
  version: 0.0.40
- alias: windows
  os: windows2019
  version: latest

update:
  canaries: 0
  max_in_flight: 32
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000

instance_groups:
- azs:
  - vsphere
  instances: 1
  jobs:
  - *add_user_cunnie
  name: xenial
  networks:
  - name: vsphere-subnet
  stemcell: xenial
  vm_type: small
- azs:
  - vsphere
  instances: 1
  jobs:
  - *add_user_cunnie
  name: bionic
  networks:
  - name: vsphere-subnet
  stemcell: bionic
  vm_type: small
- azs:
  - vsphere
  instances: 1
  jobs:
  - *add_user_cunnie
  name: jammy
  networks:
  - name: vsphere-subnet
  stemcell: jammy
  vm_type: small
- azs:
  - vsphere
  instances: 1
  jobs:
  - *add_user_cunnie
  name: noble
  networks:
  - name: vsphere-subnet
  stemcell: noble
  vm_type: small
- azs:
  - google
  instances: 0
  jobs:
  - *add_user_cunnie
  name: jammy-google
  networks:
  - name: google-private
  stemcell: jammy
  vm_type: g1-small
- azs:
  - vsphere
  instances: 1
  jobs: []
  name: windows
  networks:
  - name: vsphere-subnet
  stemcell: windows
  vm_type: compilation
