# bosh -d dummy deploy dummy.yml
name: dummy

releases:
- name: "os-conf"
  version: "22.1.2"
  url: "https://bosh.io/d/github.com/cloudfoundry/os-conf-release?v=22.1.2"
  sha1: "386293038ae3d00813eaa475b4acf63f8da226ef"

stemcells:
- alias: bionic
  os: ubuntu-bionic
  version: latest
- alias: xenial
  os: ubuntu-xenial
  version: latest
- alias: jammy
  os: ubuntu-jammy
  version: latest
- alias: windows
  os: windows2019
  version: latest

update:
  canaries: 0
  max_in_flight: 10
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000

user_add_job: &user_add_job
  name: user_add
  properties:
    users:
    - name: cunnie
      public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIWiAzxc4uovfaphO0QVC2w00YmzrogUpjAzvuqaQ9tD
        cunnie@nono.io
  release: os-conf

instance_groups:
- azs:
  - vsphere
  instances: 1
  jobs: []
  name: xenial
  networks:
  - name: vsphere-guest
  stemcell: xenial
  vm_extensions:
  # - two-cores-per-socket
  # - disk-enable-uuid
  # - change-block-tracking
  - precision-clock
  vm_type: small
- azs:
  - vsphere
  instances: 1
  jobs: []
  name: bionic
  networks:
  - name: vsphere-guest
  stemcell: bionic
  vm_extensions:
  - two-cores-per-socket
  # - anti-affinity-mysql # Difficult to do ESXi maintenance; won't migrate off
  vm_type: small
- azs:
  - vsphere
  instances: 1
  jobs: []
  name: jammy
  networks:
  - name: vsphere-guest
  stemcell: jammy
  vm_extensions:
  - disk-enable-uuid
  # - anti-affinity-mysql # Difficult to do ESXi maintenance; won't migrate off
  vm_type: small
- azs:
  - vsphere
  instances: 1
  jobs: []
  name: windows
  networks:
  - name: vsphere-guest
  stemcell: windows
  vm_type: compilation
- azs:
  - azure
  instances: 1
  jobs:
  - *user_add_job
  name: azure
  networks:
  - default:
    - dns
    - gateway
    name: azure-private
  - name: azure-public
    static_ips:
    - 20.43.176.123
  stemcell: bionic
  vm_type: standard_b1s
- azs:
  - aws
  instances: 1
  jobs:
  - *user_add_job
  name: aws
  networks:
  - default:
    - dns
    - gateway
    name: aws-private
  - name: aws-public
    static_ips:
    - 34.238.230.219
  stemcell: bionic
  vm_type: t3a.nano
