# manifest for BOSH performance testing
name: dummy

director_uuid: beb2169f-8911-453f-98ed-978adcb168c2

releases:
- name: dummy
  version: latest

stemcells:
- alias: centos
  os: centos-7
  version: latest
- alias: ubuntu
  os: ubuntu-trusty
  version: latest

update:
  canaries: 0
  max_in_flight: 10
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000

instance_groups:
- name: dummy-centos
  jobs: []
  instances: 32
  vm_type: t2.nano
  stemcell: centos
  networks:
  - name: dynamic
- name: dummy-ubuntu
  jobs: []
  instances: 32
  vm_type: t2.nano
  stemcell: ubuntu
  networks:
  - name: dynamic
