---
instance_groups:
- azs:
  - z1
  instances: 1
  jobs:
  - name: bpm
    release: bpm
  - name: ray-head
    release: ray
  - name: fastchat-controller
    release: p-llm
  - name: fastchat-openai-server
    release: p-llm
  - name: fastchat-vllm-worker
    properties:
      gpu_memory_utilization: 0.9
      model: lmsys/vicuna-7b-v1.5
      model_names: gpt-3.5-turbo,text-davinci-003,text-embedding-ada-002,vicuna-7b-v1.5
      num_gpus: 2
    release: p-llm
  - name: service-broker
    properties:
      llm_port: 5000
      service_broker_port: 5001
    release: p-llm
  name: controller
  networks:
  - name: default
  persistent_disk_type: 32G
  stemcell: default
  vm_type: large
- azs:
  - z1
  instances: 1
  jobs:
  - name: ray-worker-vllm
    properties:
      use_gpu: true
    release: ray
  name: worker-1
  networks:
  - name: default
  persistent_disk_type: 32G
  stemcell: default
  vm_extensions:
  - gpu
  vm_type: xlarge-1
- azs:
  - z1
  instances: 1
  jobs:
  - name: ray-worker-vllm
    properties:
      use_gpu: true
    release: ray
  name: worker-2
  networks:
  - name: default
  persistent_disk_type: 32G
  stemcell: default
  vm_extensions:
  - gpu
  vm_type: xlarge-2
name: llm-test
releases:
- name: ray
  version: 0+dev.41
- name: p-llm
  version: 1+dev.37
- name: bpm
  version: 1.2.5
stemcells:
- alias: default
  os: ubuntu-jammy
  version: '1.144'
update:
  canaries: 2
  canary_watch_time: 5000-60000
  max_in_flight: 5
  update_watch_time: 5000-60000
