#
# bosh -e vsphere -d multi-cpi-cck deploy multi-cpi-cck.yml -l <(lpass show --note deployments.yml) --no-redact
#
instance_groups:
- azs:
  - aws
  instances: 1
  jobs: []
  name: aws
  networks:
  - default:
    - dns
    - gateway
    name: aws-private
  - name: aws-public
    static_ips:
    - 18.210.45.12
  stemcell: bionic
  vm_type: t3.nano
- azs:
  - azure
  instances: 1
  jobs: []
  name: azure
  networks:
  - default:
    - dns
    - gateway
    name: azure-private
  - name: azure-public
    static_ips:
    - 20.198.146.138
  stemcell: bionic
  vm_type: standard_b1s
- azs:
  - google
  instances: 1
  jobs: []
  name: google
  networks:
  - name: google-private
    default:
    - gateway
    - dns
  - name: google-public
    static_ips:
    - 35.223.96.158
  stemcell: bionic
  vm_type: micro
- azs:
  - vsphere
  instances: 1
  jobs: []
  name: vsphere
  networks:
  - name: vsphere-guest
  stemcell: bionic
  vm_type: micro
name: multi-cpi-cck
releases: []
stemcells:
- alias: bionic
  os: ubuntu-bionic
  version: latest
update:
  canaries: 1
  canary_watch_time: 1000-60000
  max_in_flight: 3
  serial: false
  update_watch_time: 1000-60000
