---
# bosh -e ipv4 deploy -d nginx nginx-ipv46.yml
name: nginx

instance_groups:
- name: nginx
  instances: 1
  azs: [ z1 ]
  jobs:
  - name: nginx
    release: nginx
    properties:
      nginx_conf: |
        user  nobody vcap; # group vcap can read /var/vcap/data/nginx
        worker_processes  1;
        error_log /var/vcap/sys/log/nginx/error.log   info;
        events {
          worker_connections  1024;
        }
        http {
          include /var/vcap/packages/nginx/conf/mime.types;
          default_type  application/octet-stream;
          sendfile        on;
          ssi on;
          keepalive_timeout  65;
          server_names_hash_bucket_size 64;
          server {
            server_name _; # invalid value which will never trigger on a real hostname.
            listen [::]:80 ipv6only=off; # listen on both IPv4 & IPv6
            access_log /var/vcap/sys/log/nginx/nginx-ipv6.nono.io-access.log;
            error_log /var/vcap/sys/log/nginx/nginx-ipv6.nono.io-error.log;
            root /var/vcap/data/nginx/document_root;
            index index.shtml;
          }
        }
      pre_start: |
        #!/bin/bash -ex
        NGINX_DIR=/var/vcap/data/nginx/document_root
        if [ ! -d $NGINX_DIR ]; then
          mkdir -p $NGINX_DIR
          cd $NGINX_DIR
          cat > index.shtml <<EOF
            <html><head><title>BOSH on IPv6</title>
            </head><body>
            <h2>Welcome to BOSH on IPv6</h2>
            <h2>
            My   hostname/IP: <b><!--# echo var="HTTP_HOST" --></b><br />
            Your IP: <b><!--# echo var="REMOTE_ADDR" --></b>
            </h2>
            </body></html>
        EOF
        fi
  networks:
  - name: default
    static_ips:
    - 10.9.9.15
  - name: ipv6
    static_ips:
    - 2601:0646:0100:69f2:0000:0000:0000:000f
    default:
    - dns
    - gateway
  persistent_disk_type: default
  stemcell: ubuntu
  vm_type: small

releases:
- name: nginx
  version: latest

stemcells:
- alias: ubuntu
  os: ubuntu-xenial
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  max_in_flight: 1
  serial: false
  update_watch_time: 1000-60000
