# bosh -nd pvscsi deploy pvscsi.yml
name: pvscsi

releases:
- name: swiss-army-knife
  sha1: e0ac6bdd4ae1a0674e4e0d3b5c9c3b7f8921ff62
  url: https://github.com/cloudfoundry-community/swiss-army-knife-release/releases/download/1.0.0/swiss-army-knife-release-1.0.0.tgz
  version: 1.0.0

stemcells:
- alias: ubuntu
  os: ubuntu-bionic
  version: 1.14 # special stemcell with VMware Paravirtual SCSI controller

update:
  canaries: 0
  max_in_flight: 10
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000

instance_groups:
- name: pvscsi
  jobs:
  - name: knife
    release: swiss-army-knife
    properties:
      post_deploy: |
        #!/bin/bash
        VMW_PVSCSI_ARGS="vmw_pvscsi.cmd_per_lun=1024 vmw_pvscsi.ring_pages=32"
        if ! grep "$VMW_PVSCSI_ARGS" /proc/cmdline; then
          echo "/proc/cmdline does not have \"$VMW_PVSCSI_ARGS\""
          # Let's avoid endlessly rebooting if there's a mistake
          if ! grep "$VMW_PVSCSI_ARGS" /etc/default/grub; then
            echo "adding to '$VMW_PVSCSI_ARGS' to the kernel command line"
            sed -i "s/\"$/ $VMW_PVSCSI_ARGS &/" /etc/default/grub
            grub-mkconfig > /boot/grub/grub.cfg
            echo "rebooting"
            sleep 1 && shutdown -r
          fi
        fi

  instances: 1
#  vm_type: default
  vm_type: micro
  stemcell: ubuntu
#  azs: [z1]
  azs: [vsphere]
  networks:
#  - name: default
  - name: vsphere-guest
