apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sleeper
  name: sleeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleeper
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sleeper
    spec:
      containers:
      - image: cunnie/fedora-golang-bosh
        name: sleeper
        command: [ "sleep" ]
        args: [ "infinity" ]
        resources: {}
status: {}
