#
# bosh -e vsphere -d sslip.io deploy sslip.io.yml -l <(lpass show --note deployments.yml) --no-redact
#
# I'd like to squash the instance groups, but `instance_groups.networks` prevents it
anchors:
  user_add_job: &user_add_job
    name: user_add
    properties:
      users:
      - name: cunnie
        public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIWiAzxc4uovfaphO0QVC2w00YmzrogUpjAzvuqaQ9tD
          cunnie@nono.io
    release: os-conf
instance_groups:
- azs:
  - vsphere
  instances: 1
  jobs:
  - *user_add_job
  - name: worker
    properties:
      drain_timeout: 10m
      worker_gateway:
        host_public_key: ((tsa_host_key.public_key))
        hosts: ci.nono.io:2222
        worker_key: ((worker_key))
    release: concourse
  name: worker
  networks:
  - name: vsphere-guest
  stemcell: bionic
  vm_type: concourse-workers
name: sslip.io
releases:
- name: concourse
  sha1: 1a801bcd6fb20d310b05b2bce38b6f15327f4c9a
  url: https://bosh.io/d/github.com/concourse/concourse-bosh-release?v=7.7.0
  version: 7.7.0
- name: bpm
  sha1: 492f181f4efa08c5f0b45d22cbe54f0a20edf99e
  url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.16
  version: 1.1.16
- name: postgres
  sha1: e44bbe8f8a7cdde1cda67b202e399a239d104db6
  url: https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=43
  version: "43"
- name: os-conf
  version: "22.1.0"
  url: "https://bosh.io/d/github.com/cloudfoundry/os-conf-release?v=22.1.0"
  sha1: "7ef05f6f3ebc03f59ad8131851dbd1abd1ab3663"
stemcells:
- alias: bionic
  os: ubuntu-bionic
  version: latest
update:
  canaries: 1
  canary_watch_time: 1000-60000
  max_in_flight: 3
  serial: false
  update_watch_time: 1000-60000
