#
# bosh -e vsphere -d sslip.io deploy sslip.io.yml -l <(lpass show --note deployments.yml) --no-redact
#
# I'd like to squash the instance groups, but `instance_groups.networks` prevents it
anchors:
  user_add_job: &user_add_job
    name: user_add
    properties:
      users:
      - name: cunnie
        public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIWiAzxc4uovfaphO0QVC2w00YmzrogUpjAzvuqaQ9tD
          cunnie@nono.io
    release: os-conf
instance_groups:
- azs:
  - vsphere
  instances: 1
  jobs:
  - *user_add_job
  - name: worker
    properties:
      drain_timeout: 10m
      worker_gateway:
        host_public_key: ((tsa_host_key.public_key))
        hosts: ci.nono.io:2222
        worker_key: ((worker_key))
    release: concourse
  name: worker
  networks:
  - name: vsphere-guest
  stemcell: jammy
  vm_type: concourse-workers
name: sslip.io
releases:
- name: concourse
  sha1: 0b7c6b8ab6a0da832d91a5e30d2cc56ce80de06e
  url: https://bosh.io/d/github.com/concourse/concourse-bosh-release?v=7.10.0
  version: 7.10.0
- name: bpm
  sha1: 52c90ab6a217a77bf03b1383606557c0f56d5d8c
  url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.2.4
  version: 1.2.4
- name: postgres
  sha1: 582b1de9522077102dfa44ff7164cd8f499dbfc8
  url: https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=44
  version: "44"
- name: os-conf
  version: latest
stemcells:
- alias: jammy
  os: ubuntu-jammy
  version: latest
update:
  canaries: 1
  canary_watch_time: 1000-60000
  max_in_flight: 3
  serial: false
  update_watch_time: 1000-60000
