#
# bosh -e vsphere -d sslip.io deploy sslip.io.yml -l <(lpass show --note deployments.yml) --no-redact
#
# I'd like to squash the instance groups, but `instance_groups.networks` prevents it
anchors:
  user_add_job: &user_add_job
    name: user_add
    properties:
      users:
      - name: cunnie
        public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIWiAzxc4uovfaphO0QVC2w00YmzrogUpjAzvuqaQ9tD
          cunnie@nono.io
    release: os-conf
instance_groups:
- azs:
  - vsphere
  instances: 1
  jobs:
  - *user_add_job
  - name: worker
    properties:
      baggageclaim:
        driver: btrfs
      drain_timeout: 10m
      worker_gateway:
        host_public_key: ((tsa_host_key.public_key))
        hosts: 35.209.139.217:2222
        worker_key: ((worker_key))
    release: concourse
  name: worker
  networks:
  - name: vsphere-subnet
  stemcell: jammy
  vm_type: concourse-workers
name: sslip.io
releases:
- name: concourse
  sha1: 1cff6c589a12b8da35bc777a891b7f8dd78a9efd
  url: https://bosh.io/d/github.com/concourse/concourse-bosh-release?v=7.12.0
  version: 7.12.0
- name: bpm
  sha1: 1d2f22a5d024cb34f6d7d2da3f1ee95e4a8cdd61
  url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.4.1
  version: 1.4.1
- name: postgres
  sha1: c00282991b51ca0b3a7399c1c96fb18eff907659
  url: https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=52
  version: "52"
- name: os-conf
  version: latest
stemcells:
- alias: jammy
  os: ubuntu-jammy
  version: latest
update:
  canaries: 1
  canary_watch_time: 1000-60000
  max_in_flight: 3
  serial: false
  update_watch_time: 1000-60000
