# bosh -nd stress-nsx deploy stress-nsx.yml
name: stress-nsx

releases: []

stemcells:
- alias: jammy
  os: ubuntu-jammy
  version: latest

update:
  canaries: 0
  max_in_flight: 10
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000

instance_groups:
- azs:
  - vsphere-nsx
  instances: 32
  jobs: []
  name: zergling
  networks:
  - name: vsphere-nsx
  stemcell: jammy
  vm_type: micro
