# bosh ucc cloud-config.yml
# 3,$!bosh int -
azs:
- cloud_properties:
    datacenters:
    - clusters:
      - nested:
          resource_pool: CPI-perf
      name: dc
  name: vsphere
compilation:
  az: vsphere
  network: LS.0.0
  reuse_compilation_vms: true
  vm_type: compilation
  workers: 15
disk_types:
- disk_size: 1024
  name: default
networks:
- name: LS.0.0
  subnets:
  - azs:
    - vsphere
    cloud_properties:
      name: LS.0.0
    dns:
    - 10.9.16.1
    - 8.8.8.8
    gateway: 10.8.1.1
    range: 10.8.1.0/24
    reserved: []
  type: manual
vm_types:
- cloud_properties:
    cpu: 1
    disk: 10240
    ram: 1024
    datastores:
    - NAS-0
  name: micro
- cloud_properties:
    cpu: 4
    disk: 16_384
    ram: 4096
  name: compilation
