# fly -t nono sp -p stemcell -c ~/workspace/deployments/ci/pipeline-stemcell.yml -l <(lpass show --note deployments.yml)
# fly -t nono expose-pipeline -p stemcell
# fly -t nono unpause-pipeline -p stemcell

# :,$!bosh int -
jobs:
- name: upload-jammy-vsphere
  plan:
  - get: stemcell
    resource: stemcell-jammy-vsphere
    trigger: true
  - get: cunnie-deployments
  - file: cunnie-deployments/ci/tasks/upload-stemcell.yml
    params:
      BOSH_CLIENT: admin
      BOSH_CLIENT_SECRET: ((admin_password))
      BOSH_ENVIRONMENT: bosh-vsphere.nono.io
    task: upload-stemcell
resources:
- name: cunnie-deployments
  source:
    uri: https://github.com/cunnie/deployments.git
  type: git
- name: stemcell-jammy-vsphere
  source:
    name: bosh-vsphere-esxi-ubuntu-jammy-go_agent
  type: bosh-io-stemcell
