# fly -t nono sp -p dockerfiles -c pipeline-dockerfiles.yml
# fly -t nono ep -p dockerfiles
# fly -t nono up -p dockerfiles

resources:
# The repo with our fedora-golang-bosh Dockerfile
- name: deployments
  type: git
  icon: github
  source:
    uri: https://github.com/cunnie/deployments.git
    paths:
    - ci

# Where we will push the fedora-golang-bosh Docker image
- name: fedora-golang-bosh
  type: registry-image
  icon: docker
  source:
    repository: cunnie/fedora-golang-bosh
    username: cunnie
    password: ((docker_token))
    tag: latest

jobs:
- name: build-and-push-fedora-golang-bosh
  plan:
  - get: deployments
    trigger: true
  - task: build-task-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: deployments
      outputs:
      - name: image
      params:
        CONTEXT: deployments/ci
        IMAGE_PLATFORM: linux/arm64,linux/amd64
        OUTPUT_OCI: true
      run:
        path: build
  - put: fedora-golang-bosh
    params:
      image: image/image
