# fly -t nono sp -p platform-automation -c ~/workspace/deployments/ci/pipeline-platform-automation.yml -l <(lpass show --note deployments.yml)
# fly -t nono expose-pipeline -p platform-automation
# fly -t nono unpause-pipeline -p platform-automation

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

- name: s3-with-arn
  type: docker-image
  source:
    repository: concourse/s3-resource
    tag: 1.2.1-ubuntu

resources:
- name: platform-automation-pivnet
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: platform-automation
    product_version: 5\.(.*)
    sort_by: semver

- name: platform-automation-tasks
  type: s3-with-arn
  source:
    access_key_id: ((s3_with_role.access_key_id))
    secret_access_key: ((s3_with_role.secret_access_key))
    bucket: ((s3_pivnet_products_bucket))
    region_name: ((s3_region_name))
    endpoint: https://s3.nono.io:9000
    regexp: platform-automation-tasks-(.*).zip

- name: platform-automation-image
  type: s3-with-arn
  source:
    access_key_id: ((s3_with_role.access_key_id))
    secret_access_key: ((s3_with_role.secret_access_key))
    bucket: ((s3_pivnet_products_bucket))
    region_name: ((s3_region_name))
    endpoint: https://s3.nono.io:9000
    regexp: platform-automation-image-(.*).tgz

- name: installation
  type: s3-with-arn
  source:
    access_key_id: ((s3_with_role.access_key_id))
    secret_access_key: ((s3_with_role.secret_access_key))
    bucket: ((s3_pivnet_products_bucket))
    region_name: ((s3_region_name))
    endpoint: https://s3.nono.io:9000
    regexp: installation-(.*).zip

- name: opsman-ova
  type: s3-with-arn
  source:
    access_key_id: ((s3_with_role.access_key_id))
    secret_access_key: ((s3_with_role.secret_access_key))
    bucket: ((s3_pivnet_products_bucket))
    region_name: ((s3_region_name))
    endpoint: https://s3.nono.io:9000
    regexp: ops-manager-vsphere-(.*)\+LTS-T.ova

- name: config
  type: git
  source:
    branch: main
    private_key: ((plat-auto-pipes-deploy-key.private_key))
    uri: git@github.com:cunnie/tas.nono.io.git

- name: vars
  type: git
  source:
    branch: main
    uri: git@github.com:cunnie/tas.nono.io.git
    private_key: ((plat-auto-pipes-deploy-key.private_key))

- name: daily
  type: time
  source:
    interval: 24h
#
# This task is used in multiple jobs
# The yaml anchor "*prepare-tasks-with-secrets" is used in its place
prepare-tasks-with-secrets: &prepare-tasks-with-secrets
  task: prepare-tasks-with-secrets
  image: platform-automation-image
  file: platform-automation-tasks/tasks/prepare-tasks-with-secrets.yml
  params:
    CONFIG_PATHS: config
  input_mapping:
    tasks: platform-automation-tasks
  output_mapping:
    tasks: platform-automation-tasks

jobs:
- name: export-installation
  serial: true
  plan:
    - get: platform-automation-image
      params:
        globs: ["*image*.tgz"]
        unpack: true
    - get: platform-automation-tasks
      params:
        globs: ["*tasks*.zip"]
        unpack: true
    - get: env
      resource: config
    - task: export-installation
      image: platform-automation-image
      file: platform-automation-tasks/tasks/export-installation.yml
    - put: installation
      params:
        file: installation/installation-*.zip

- name: delete-opsman
  serial_groups:
  - opsman
  plan:
  - get: platform-automation-image
    params:
      unpack: true
  - get: platform-automation-tasks
    params:
      unpack: true
  - get: config
  - *prepare-tasks-with-secrets
  - task: delete-opsman
    image: platform-automation-image
    file: platform-automation-tasks/tasks/delete-vm.yml
    input_mapping:
      env: config
      secrets: config
      state: config
  ensure:
    do:
    - task: make-commit
      image: platform-automation-image
      file: platform-automation-tasks/tasks/make-git-commit.yml
      input_mapping:
        repository: config
        file-source: generated-state
      output_mapping:
        repository-commit: config-commit
      params:
        FILE_SOURCE_PATH: state.yml
        FILE_DESTINATION_PATH: state.yml
        GIT_AUTHOR_EMAIL: "an-important-bot@broadcom.com"
        GIT_AUTHOR_NAME: "Platform Automation Toolkit Bot"
        COMMIT_MESSAGE: 'Update state file'
    - put: config
      params:
        repository: config-commit
        merge: true

- name: upgrade-opsman
  serial_groups:
  - opsman
  plan:
  - get: platform-automation-image
    params:
      unpack: true
  - get: platform-automation-tasks
    params:
      unpack: true
  - get: downloaded-product
    resource: opsman-ova
  - get: config
    passed:
    - delete-opsman
    trigger: true
  - get: installation
  - *prepare-tasks-with-secrets
  - task: upgrade-opsman
    image: platform-automation-image
    file: platform-automation-tasks/tasks/upgrade-opsman.yml
    input_mapping:
      env: config
      image: downloaded-product
      secrets: config
      state: config
  ensure:
    do:
    - task: make-commit
      image: platform-automation-image
      file: platform-automation-tasks/tasks/make-git-commit.yml
      input_mapping:
        repository: config
        file-source: generated-state
      output_mapping:
        repository-commit: config-commit
      params:
        FILE_SOURCE_PATH: state.yml
        FILE_DESTINATION_PATH: state.yml
        GIT_AUTHOR_EMAIL: "an-important-bot@broadcom.com"
        GIT_AUTHOR_NAME: "Platform Automation Toolkit Bot"
        COMMIT_MESSAGE: 'Update state file'
    - put: config
      params:
        repository: config-commit
        merge: true

- name: install-ops-manager
  serial: true
  plan:
    - get: platform-automation-image
      params:
        unpack: true
    - get: platform-automation-tasks
      params:
        unpack: true
    - get: downloaded-product
      resource: opsman-ova
    - get: config
    - get: vars
    - *prepare-tasks-with-secrets
    - task: create-vm
      image: platform-automation-image
      file: platform-automation-tasks/tasks/create-vm.yml
      params:
        VARS_FILES: vars/vars.yml
      input_mapping:
        state: config
        image: downloaded-product
      ensure:
        do:
          - task: make-commit
            image: platform-automation-image
            file: platform-automation-tasks/tasks/make-git-commit.yml
            input_mapping:
              repository: config
              file-source: generated-state
            output_mapping:
              repository-commit: config-commit
            params:
              FILE_SOURCE_PATH: state.yml
              FILE_DESTINATION_PATH: state.yml
              GIT_AUTHOR_EMAIL: "an-important-bot@broadcom.com"
              GIT_AUTHOR_NAME: "Platform Automation Toolkit Bot"
              COMMIT_MESSAGE: 'Update state file'
          - put: config
            params:
              repository: config-commit
              merge: true

- name: download-upload-and-stage-tas
  serial: true
  plan:
  - in_parallel:
    - get: platform-automation-image
      params:
        globs: ["*image*.tgz"]
        unpack: true
    - get: platform-automation-tasks
      params:
        globs: ["*tasks*.zip"]
        unpack: true
    - get: config
  - *prepare-tasks-with-secrets
  - task: download-tas
    image: platform-automation-image
    file: platform-automation-tasks/tasks/download-product.yml
    input_mapping:
      config: config
    params:
      CONFIG_FILE: download-tas.yml
    output_mapping:
      downloaded-product: tas-product
      downloaded-stemcell: tas-stemcell
  - task: upload-tas-stemcell
    image: platform-automation-image
    file: platform-automation-tasks/tasks/upload-stemcell.yml
    input_mapping:
      env: config
      stemcell: tas-stemcell
    params:
      ENV_FILE: env.yml
  - task: upload-and-stage-tas
    image: platform-automation-image
    file: platform-automation-tasks/tasks/upload-and-stage-product.yml
    input_mapping:
      product: tas-product
      env: config

- name: configure-tas
  serial: true
  plan:
    - in_parallel:
      - get: platform-automation-image
        passed: [download-upload-and-stage-tas]
        trigger: true
        params:
          globs: ["*image*.tgz"]
          unpack: true
      - get: platform-automation-tasks
        params:
          globs: ["*tasks*.zip"]
          unpack: true
      - get: config
        passed: [download-upload-and-stage-tas]
    - *prepare-tasks-with-secrets
    - task: configure-tas
      image: platform-automation-image
      file: platform-automation-tasks/tasks/configure-product.yml
      input_mapping:
        config: config
        env: config
      params:
        CONFIG_FILE: tas-config.yml

- name: apply-changes
  serial: true
  plan:
    - in_parallel:
      - get: platform-automation-image
        params:
          globs: ["*image*.tgz"]
          unpack: true
      - get: platform-automation-tasks
        params:
          globs: ["*tasks*.zip"]
          unpack: true
      - get: config
        passed: [configure-tas]
    - *prepare-tasks-with-secrets
    - task: apply-changes
      image: platform-automation-image
      file: platform-automation-tasks/tasks/apply-changes.yml
      input_mapping:
        env: config

- name: fetch-platform-automation
  # We use the pivnet resource to bootstrap the pipeline,
  # and because this product is part of the pipeline, not the foundation
  plan:
  - get: platform-automation-pivnet
    trigger: true
  - in_parallel:
    - put: platform-automation-tasks
      params:
        file: platform-automation-pivnet/*tasks*.zip
    - put: platform-automation-image
      params:
        file: platform-automation-pivnet/*image*.tgz

- name: fetch-opsman
  # We use the pivnet resource to bootstrap the pipeline,
  # and because this product is part of the pipeline, not the foundation
  plan:
    - get: platform-automation-image
      params:
        unpack: true
    - get: platform-automation-tasks
      params:
        unpack: true
    - get: config
    - get: vars
    - get: daily
      trigger: true
    - *prepare-tasks-with-secrets
    - task: download-product
      image: platform-automation-image
      file: platform-automation-tasks/tasks/download-product.yml
      params:
        CONFIG_FILE: download-opsman.yml
    - put: opsman-ova
      params:
        file: downloaded-product/ops-manager-vsphere*.ova
