# fly -t nono sp -p ozymandias-pipeline -c pipeline-ozymandias.yml
#
# Pipeline to periodically check Concourse-Vault
# integration via secret interpolation
resources:
- name: daily
  type: time # default source.interval is one day
jobs:
- name: ozymandias-job
  plan:
  - get: daily
    trigger: true
  - task: ozymandias-task
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: fedora
      run:
        path: echo
        args:
        - "Ozymandias says:"
        - ((ozymandias-secret))
