concourse:
  web:
    externalUrl: https://ci.nono.io
    localAuth:
      enabled: false
    vault:
      enabled: true
      url: https://vault.nono.io
      authBackend: "approle"
      useAuthParam: true
    auth:
      duration: 240h
      mainTeam:
        github:
          org: blabbertabber
      github:
        enabled: true
web:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
    hosts:
    - ci.nono.io
    tls:
    - hosts:
      - ci.nono.io
      secretName: ci.nono.io
worker:
  # The following should be `true` (default) for almost everyone. I don't want workers
  # because I bring my own worker separately, which is on vSphere not GKE.
  enabled: false
secrets:
  localUsers:
  hostKey: change-me
  hostKeyPub: change-me
  sessionSigningKey: change-me
  workerKey: change-me
  workerKeyPub: change-me
  githubClientId: d4d77ce34ecc620d5220
  githubClientSecret: change-me
