concourse:
  web:
    externalUrl: https://ci.nono.io
    localAuth:
      enabled: false
    kubernetes:
      enabled: false
    vault:
      enabled: true
      url: https://vault.nono.io:443
      authBackend: approle
      useAuthParam: true
    auth:
      duration: 240h
      mainTeam:
        github:
          org: blabbertabber
      github:
        enabled: true
web:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
    - ci.nono.io
    tls:
    - hosts:
      - ci.nono.io
      secretName: ci.nono.io
worker:
  # The following should be `true` (default) for almost everyone. I don't want workers
  # because I bring my own worker separately, which is on vSphere not GKE.
  enabled: false
secrets:
  # If the value is "change-me", that means it's overridden from the command line,
  # e.g. "helm upgrade ci-nono-io concourse/concourse ... --set secrets.hostKey='xxx' ... "
  localUsers:
  githubClientId: fc24016a9c3267843698
  githubClientSecret: change-me
  hostKey: change-me
  hostKeyPub: change-me
  workerKey: change-me
  workerKeyPub: change-me
  sessionSigningKey: change-me
  vaultAuthParam: change-me
