# bosh -d dummy1 deploy dummy1.yml
name: dummy1

releases: []

stemcells:
- alias: jammy
  os: ubuntu-jammy
  version: latest

update:
  canaries: 0
  max_in_flight: 10
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000

instance_groups:
- azs:
  - vsphere
  instances: 10
  jobs: []
  name: jammy
  networks:
  - name: vsphere-guest
  stemcell: jammy
  vm_type: micro
