# bosh -d dummy2 deploy dummy2.yml
name: dummy2

releases: []

stemcells:
- alias: jammy
  os: ubuntu-jammy
  version: latest
- alias: xenial
  os: ubuntu-xenial
  version: latest

update:
  canaries: 0
  max_in_flight: 32
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000

instance_groups:
- azs:
  - vsphere
  instances: 10
  jobs: []
  name: stemcells
  networks:
  - name: vsphere-guest
  stemcell: jammy
  vm_type: micro
